-- Add caption-confirmed gallery photos and owner-review drafts after the initial seed.
-- Existing product photos are appended; this migration does not change publication, prices or availability.
update public.products set photos = photos || '{"static":"photos/archive_004_orehovy.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'orehovy' and not photos @> '[{"static":"photos/archive_004_orehovy.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_022_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'molochnaya-devochka' and not photos @> '[{"static":"photos/archive_022_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_069_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'molochnaya-devochka' and not photos @> '[{"static":"photos/archive_069_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_077_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'molochnaya-devochka' and not photos @> '[{"static":"photos/archive_077_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_078_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'molochnaya-devochka' and not photos @> '[{"static":"photos/archive_078_molochnaya-devochka.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_063_assorti.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'assorti' and not photos @> '[{"static":"photos/archive_063_assorti.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_080_merengovy-rulet.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'merengovy-rulet' and not photos @> '[{"static":"photos/archive_080_merengovy-rulet.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_081_merengovy-rulet.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'merengovy-rulet' and not photos @> '[{"static":"photos/archive_081_merengovy-rulet.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_085_slivochno-karamelny.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'slivochno-karamelny' and not photos @> '[{"static":"photos/archive_085_slivochno-karamelny.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_025_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'medovik' and not photos @> '[{"static":"photos/archive_025_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_083_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'medovik' and not photos @> '[{"static":"photos/archive_083_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_098_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'medovik' and not photos @> '[{"static":"photos/archive_098_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_099_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'medovik' and not photos @> '[{"static":"photos/archive_099_medovik.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_039_kurnik.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'kurnik' and not photos @> '[{"static":"photos/archive_039_kurnik.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_060_kurnik.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'kurnik' and not photos @> '[{"static":"photos/archive_060_kurnik.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_001_zefirnye-tsvety.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'zefirnye-tsvety' and not photos @> '[{"static":"photos/archive_001_zefirnye-tsvety.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;
update public.products set photos = photos || '{"static":"photos/archive_002_zefirnye-tsvety.jpg","desktop":"50% 50%","mobile":"50% 50%"}'::jsonb where slug = 'zefirnye-tsvety' and not photos @> '[{"static":"photos/archive_002_zefirnye-tsvety.jpg","desktop":"50% 50%","mobile":"50% 50%"}]'::jsonb;

-- Drafts remain hidden until Milana reviews the offering and its photos in the admin panel.
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('trehsloynyy-pirog','Трёхслойный пирог с курагой и орехами','sweet',200,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('fruktovyy-tort','Фруктовый торт','cakes',210,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('yagodno-fruktovyy-tort','Ягодно-фруктовый торт','cakes',220,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('pancho','Торт «Панчо»','cakes',230,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('brusletiki','Слоёные рулетики «Бруслетики» с брусникой','desserts',240,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('zefirnyy-sendvich','Зефирный сэндвич','desserts',250,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('semga-brokkoli','Пирог с сёмгой и брокколи','savory',260,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('zefirnaya-roza','Зефирная роза в колбе','desserts',270,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('spartak','Торт «Спартак»','cakes',280,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('nezhnost','Торт «Нежность»','cakes',290,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('shokoladnye-maffiny','Шоколадные маффины с творожным кремом','desserts',300,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('rafaello','Торт «Рафаэлло»','cakes',310,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('muchnaya-halva','Мучная халва','desserts',320,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('merengi','Меренги','desserts',330,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('biskvitno-fruktovyy-tort','Бисквитно-фруктовый торт','cakes',340,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('napoleon','Торт «Наполеон» с ягодами','cakes',350,false,'unconfirmed') on conflict (slug) do nothing;
insert into public.products (slug,title,category_id,sort_order,published,availability) values ('shokoladnyy-tort-ananas','Шоколадный торт с ананасом','cakes',360,false,'unconfirmed') on conflict (slug) do nothing;
